package com.iridium126.createmanaindustry.worldgen.markov;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.Map;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MarkovModelTest {
    private static MarkovModel model() throws Exception {
        try (var xml = MarkovModelTest.class.getResourceAsStream("/data/createmanaindustry/markov/natural_small_tree.xml")) {
            assertNotNull(xml);
            return MarkovModel.load(xml, 19, 19, 18);
        }
    }

    @Test void upstreamGoldenVoxelsIncludingSignedSeedBoundaries() throws Exception {
        // SHA256 of raw upstream state arrays, independently generated by ReferenceBenchmark.
        var expected = Map.of(
                0, "3be263b5ccf452d37ebb7dc020a5ad948d64f16f9b129b137f8f00236b4f6dec",
                1, "18cbaa330d879c7a3420d5d8a0d2306f70be7615f1dece5500866b5997387e13",
                7, "d3176d0de4a8c162cb807579408c779d016f1f3e3a15ef8e4ea3b887ddfb7796",
                31, "e9138f9bcadbc58e14416a736ad1cdfeb64ea581fb5660d167353bc6b2fa9225",
                42, "b5e26dd12501deb35f4ce5d83a3f7c6a018c698e9f50953c7e45731a8a35767c",
                137, "768773058f977b814977097eaa46033a9b526da130453001124ec0b9c1c9634c",
                2026, "185c2fd477833bfe649303e1a609ca76b43ceff1c502677010110a4f1ae7b2de",
                -1, "18cbaa330d879c7a3420d5d8a0d2306f70be7615f1dece5500866b5997387e13",
                Integer.MIN_VALUE, "cdd856968b322af0065ab2a84ee9cafed81932e98c6b9d50ec3baf9c1c69336d",
                Integer.MAX_VALUE, "cdd856968b322af0065ab2a84ee9cafed81932e98c6b9d50ec3baf9c1c69336d");
        var model = model();
        for (var entry : expected.entrySet()) assertEquals(entry.getValue(),
                HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(model.generate(entry.getKey(), 1000))),
                "Upstream mismatch for seed " + entry.getKey());
    }

    @Test void simultaneousWorldgenWorkersDoNotShareState() throws Exception {
        var model = model();
        try (var executor = Executors.newFixedThreadPool(4)) {
            var jobs = new java.util.ArrayList<java.util.concurrent.Future<byte[]>>();
            for (int i = 0; i < 32; i++) { int seed = i; jobs.add(executor.submit(() -> model.generate(seed, 1000))); }
            for (int i = 0; i < jobs.size(); i++) assertArrayEquals(model.generate(i, 1000), jobs.get(i).get());
        }
    }

    @Test void rejectsUnsupportedSyntaxAndIncompleteRuns() throws Exception {
        var model = model();
        assertThrows(IllegalStateException.class, () -> model.generate(0, 1));
        for (String body : new String[] {"<wfc/>", "<one in='B' out='X' symmetry='(xyz)'/>",
                "<prl in='B' out='X' p='NaN'/>", "<prl in='B' out='X' search='True'/>"}) {
            var xml = new ByteArrayInputStream(("<sequence values='BX' symmetry='()'>" + body + "</sequence>").getBytes(StandardCharsets.UTF_8));
            assertThrows(IllegalArgumentException.class, () -> MarkovModel.load(xml, 19, 19, 18));
        }
    }

    @Test void developersCanCompileAdditionalNodesWithoutChangingTheInterpreter() {
        var xml = new ByteArrayInputStream("<sequence values='BX' symmetry='()'><seed/></sequence>".getBytes(StandardCharsets.UTF_8));
        var model = MarkovModel.load(xml, 1, 1, 1, Map.of("seed", (element, compiler) -> execution -> {
            execution.step();
            execution.state[0] = (byte)compiler.value('X');
        }));
        assertArrayEquals(new byte[] {1}, model.generate(0, 1));
    }
}
